SELECT * WHERE {  ?v0 <http://xmlns.com/foaf/homepage> <http://db.uwaterloo.ca/~galuc/wsdbm/Website2948> .  ?v0 <http://ogp.me/ns#title> ?v2 .  ?v0 <http://schema.org/contentRating> ?v3 .  }
SELECT * WHERE {  ?v0 <http://purl.org/goodrelations/includes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product19173> .  ?v0 <http://purl.org/goodrelations/price> ?v2 .  ?v0 <http://schema.org/eligibleQuantity> ?v3 .  ?v0 <http://schema.org/priceValidUntil> ?v4 .  }
SELECT * WHERE {  ?v2 <http://schema.org/eligibleRegion> <http://db.uwaterloo.ca/~galuc/wsdbm/Country7> .  ?v2 <http://purl.org/goodrelations/includes> ?v3 .  ?v0 <http://purl.org/goodrelations/offers> ?v2 .  ?v2 <http://purl.org/goodrelations/validThrough> ?v4 .  ?v2 <http://schema.org/eligibleQuantity> ?v6 .  ?v2 <http://schema.org/priceValidUntil> ?v9 .  ?v0 <http://purl.org/goodrelations/description> ?v1 .  ?v0 <http://schema.org/aggregateRating> ?v5 .  ?v0 <http://schema.org/faxNumber> ?v8 .  ?v0 <http://schema.org/telephone> ?v10 .  }
SELECT * WHERE {  ?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory14> .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v1 <http://ogp.me/ns#tag> ?v2 .  ?v1 <http://ogp.me/ns#title> ?v4 .  ?v1 <http://schema.org/expires> ?v7 .  ?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v3 .  ?v3 <http://ogp.me/ns#tag> ?v2 .  ?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .  }
SELECT * WHERE {  ?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory10> .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v1 <http://purl.org/stuff/rev#hasReview> ?v3 .  ?v1 <http://schema.org/contentSize> ?v9 .  ?v3 <http://purl.org/stuff/rev#rating> ?v4 .  ?v3 <http://purl.org/stuff/rev#reviewer> ?v5 .  ?v3 <http://purl.org/stuff/rev#text> ?v6 .  ?v3 <http://purl.org/stuff/rev#title> ?v7 .  ?v3 <http://purl.org/stuff/rev#totalVotes> ?v8 .  }
SELECT * WHERE {  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/gender> <http://db.uwaterloo.ca/~galuc/wsdbm/Gender1> .  ?v0 <http://xmlns.com/foaf/givenName> ?v1 .  ?v0 <http://schema.org/nationality> ?v3 .  ?v2 <http://www.geonames.org/ontology#parentCountry> ?v3 .  ?v4 <http://schema.org/eligibleRegion> ?v3 .  }
SELECT * WHERE {  ?v2 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/Role2> .  ?v0 <http://schema.org/author> ?v2 .  ?v2 <http://schema.org/email> ?v5 .  ?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/friendOf> ?v2 .  ?v0 <http://ogp.me/ns#tag> ?v1 .  ?v0 <http://schema.org/contentSize> ?v4 .  }
SELECT * WHERE {  ?v0 <http://xmlns.com/foaf/age> <http://db.uwaterloo.ca/~galuc/wsdbm/AgeGroup6> .  ?v0 <http://xmlns.com/foaf/givenName> ?v2 .  ?v0 <http://schema.org/email> ?v3 .  ?v0 <http://schema.org/nationality> ?v4 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/friendOf> ?v0 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/gender> ?v5 .  }
SELECT * WHERE {  ?v2 <http://schema.org/eligibleRegion> <http://db.uwaterloo.ca/~galuc/wsdbm/Country23> .  ?v0 <http://purl.org/goodrelations/offers> ?v2 .  ?v2 <http://purl.org/goodrelations/price> ?v3 .  ?v2 <http://purl.org/goodrelations/validFrom> ?v4 .  ?v2 <http://purl.org/goodrelations/validThrough> ?v5 .  ?v0 <http://purl.org/goodrelations/name> ?v1 .  ?v0 <http://schema.org/contactPoint> ?v8 .  ?v0 <http://schema.org/email> ?v10 .  ?v0 <http://schema.org/openingHours> ?v11 .  ?v6 <http://purl.org/stuff/rev#reviewer> ?v8 .  ?v6 <http://purl.org/stuff/rev#rating> ?v7 .  }
SELECT * WHERE {  ?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic248> .  ?v0 <http://purl.org/stuff/rev#hasReview> ?v2 .  ?v0 <http://schema.org/contentRating> ?v6 .  ?v0 <http://schema.org/description> ?v7 .  ?v0 <http://schema.org/keywords> ?v8 .  ?v2 <http://purl.org/stuff/rev#rating> ?v3 .  ?v2 <http://purl.org/stuff/rev#reviewer> ?v4 .  ?v2 <http://purl.org/stuff/rev#totalVotes> ?v5 .  }
SELECT * WHERE {  <http://db.uwaterloo.ca/~galuc/wsdbm/City63> <http://www.geonames.org/ontology#parentCountry> ?v1 .  ?v2 <http://schema.org/eligibleRegion> ?v1 .  ?v4 <http://schema.org/nationality> ?v1 .  ?v2 <http://schema.org/eligibleQuantity> ?v3 .  }
SELECT * WHERE {  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/gender> <http://db.uwaterloo.ca/~galuc/wsdbm/Gender1> .  ?v0 <http://xmlns.com/foaf/familyName> ?v1 .  ?v0 <http://xmlns.com/foaf/givenName> ?v2 .  ?v0 <http://schema.org/email> ?v3 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/userId> ?v5 .  }
SELECT * WHERE {  ?v1 <http://schema.org/eligibleRegion> <http://db.uwaterloo.ca/~galuc/wsdbm/Country20> .  ?v0 <http://purl.org/goodrelations/offers> ?v1 .  ?v1 <http://purl.org/goodrelations/price> ?v2 .  ?v0 <http://schema.org/contactPoint> ?v3 .  ?v0 <http://schema.org/email> ?v5 .  ?v0 <http://schema.org/legalName> ?v6 .  ?v0 <http://schema.org/openingHours> ?v7 .  ?v0 <http://schema.org/paymentAccepted> ?v8 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory11> .  ?v0 <http://ogp.me/ns#tag> ?v1 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory5> .  ?v0 <http://ogp.me/ns#tag> ?v1 .  ?v0 <http://schema.org/keywords> ?v3 .  }
SELECT * WHERE {  ?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic242> .  ?v0 <http://purl.org/stuff/rev#hasReview> ?v2 .  ?v0 <http://schema.org/contentRating> ?v8 .  ?v2 <http://purl.org/stuff/rev#rating> ?v3 .  ?v2 <http://purl.org/stuff/rev#reviewer> ?v4 .  ?v2 <http://purl.org/stuff/rev#text> ?v5 .  ?v2 <http://purl.org/stuff/rev#title> ?v6 .  ?v2 <http://purl.org/stuff/rev#totalVotes> ?v7 .  }
SELECT * WHERE {  ?v0 <http://xmlns.com/foaf/age> <http://db.uwaterloo.ca/~galuc/wsdbm/AgeGroup3> .  ?v2 <http://schema.org/author> ?v0 .  ?v0 <http://schema.org/telephone> ?v3 .  }
SELECT * WHERE {  ?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/Genre18> .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v3 .  ?v0 <http://xmlns.com/foaf/homepage> ?v1 .  ?v2 <http://purl.org/goodrelations/includes> ?v0 .  ?v0 <http://schema.org/caption> ?v5 .  ?v0 <http://schema.org/contentRating> ?v6 .  ?v0 <http://schema.org/text> ?v7 .  ?v8 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .  }
SELECT * WHERE {  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/gender> <http://db.uwaterloo.ca/~galuc/wsdbm/Gender1> .  ?v0 <http://xmlns.com/foaf/homepage> ?v1 .  ?v0 <http://schema.org/nationality> ?v8 .  ?v2 <http://schema.org/eligibleRegion> ?v8 .  ?v2 <http://purl.org/goodrelations/includes> ?v3 .  ?v4 <http://purl.org/goodrelations/offers> ?v2 .  ?v2 <http://purl.org/goodrelations/serialNumber> ?v5 .  ?v2 <http://purl.org/goodrelations/validThrough> ?v6 .  ?v2 <http://schema.org/eligibleQuantity> ?v7 .  }
SELECT * WHERE {  <http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1084> <http://purl.org/goodrelations/offers> ?v0 .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v0 <http://purl.org/goodrelations/price> ?v3 .  ?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .  ?v0 <http://schema.org/eligibleQuantity> ?v5 .  ?v0 <http://schema.org/eligibleRegion> ?v6 .  ?v0 <http://schema.org/priceValidUntil> ?v7 .  }
SELECT * WHERE {  <http://db.uwaterloo.ca/~galuc/wsdbm/Purchase105791> <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseFor> ?v3 .  ?v2 <http://purl.org/goodrelations/includes> ?v3 .  ?v2 <http://purl.org/goodrelations/validThrough> ?v4 .  ?v2 <http://schema.org/eligibleQuantity> ?v5 .  ?v2 <http://schema.org/eligibleRegion> ?v1 .  ?v0 <http://www.geonames.org/ontology#parentCountry> ?v1 .  ?v6 <http://schema.org/nationality> ?v1 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory11> .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v2 .  ?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .  }
SELECT * WHERE {  ?v4 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic41> .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v4 .  ?v0 <http://xmlns.com/foaf/age> ?v1 .  ?v0 <http://xmlns.com/foaf/familyName> ?v2 .  ?v0 <http://xmlns.com/foaf/homepage> ?v3 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory0> .  ?v0 <http://xmlns.com/foaf/homepage> ?v1 .  ?v0 <http://schema.org/expires> ?v3 .  }
SELECT * WHERE {  ?v0 <http://schema.org/eligibleRegion> <http://db.uwaterloo.ca/~galuc/wsdbm/Country7> .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v2 <http://purl.org/goodrelations/offers> ?v0 .  ?v0 <http://purl.org/goodrelations/validFrom> ?v3 .  ?v0 <http://purl.org/goodrelations/validThrough> ?v4 .  ?v0 <http://schema.org/eligibleQuantity> ?v5 .  ?v0 <http://schema.org/priceValidUntil> ?v7 .  }
SELECT * WHERE {  ?v0 <http://xmlns.com/foaf/age> <http://db.uwaterloo.ca/~galuc/wsdbm/AgeGroup8> .  ?v0 <http://xmlns.com/foaf/givenName> ?v2 .  ?v0 <http://schema.org/email> ?v3 .  ?v0 <http://schema.org/telephone> ?v4 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/subscribes> ?v5 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/userId> ?v6 .  }
SELECT * WHERE {  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre80> .  ?v0 <http://xmlns.com/foaf/homepage> ?v1 .  ?v0 <http://ogp.me/ns#tag> ?v2 .  ?v0 <http://schema.org/keywords> ?v3 .  }
SELECT * WHERE {  ?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre33> .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v1 <http://schema.org/contentSize> ?v2 .  ?v1 <http://schema.org/description> ?v3 .  }
SELECT * WHERE {  ?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory6> .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v0 <http://purl.org/goodrelations/validThrough> ?v2 .  }
SELECT * WHERE {  <http://db.uwaterloo.ca/~galuc/wsdbm/User30576> <http://schema.org/nationality> ?v3 .  ?v0 <http://schema.org/eligibleRegion> ?v3 .  ?v0 <http://purl.org/goodrelations/serialNumber> ?v1 .  ?v0 <http://purl.org/goodrelations/validThrough> ?v2 .  }
SELECT * WHERE {  ?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory8> .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v1 <http://ogp.me/ns#tag> ?v2 .  ?v1 <http://schema.org/contentRating> ?v6 .  ?v1 <http://schema.org/description> ?v7 .  ?v1 <http://schema.org/keywords> ?v8 .  ?v1 <http://schema.org/text> ?v9 .  ?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v4 .  ?v10 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v1 .  ?v4 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v5 .  }
SELECT * WHERE {  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/gender> <http://db.uwaterloo.ca/~galuc/wsdbm/Gender0> .  ?v0 <http://xmlns.com/foaf/age> ?v1 .  ?v0 <http://xmlns.com/foaf/familyName> ?v2 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/follows> ?v0 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/subscribes> ?v4 .  }
SELECT * WHERE {  <http://db.uwaterloo.ca/~galuc/wsdbm/City63> <http://www.geonames.org/ontology#parentCountry> ?v1 .  ?v2 <http://schema.org/eligibleRegion> ?v1 .  ?v4 <http://schema.org/nationality> ?v1 .  ?v2 <http://schema.org/eligibleQuantity> ?v3 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory11> .  ?v0 <http://ogp.me/ns#tag> ?v1 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v3 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory3> .  ?v0 <http://ogp.me/ns#tag> ?v1 .  ?v0 <http://purl.org/stuff/rev#hasReview> ?v4 .  ?v0 <http://schema.org/contentSize> ?v9 .  ?v0 <http://schema.org/description> ?v10 .  ?v0 <http://schema.org/keywords> ?v11 .  ?v12 <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseFor> ?v0 .  ?v2 <http://ogp.me/ns#tag> ?v1 .  ?v4 <http://purl.org/stuff/rev#rating> ?v5 .  ?v4 <http://purl.org/stuff/rev#reviewer> ?v6 .  ?v4 <http://purl.org/stuff/rev#text> ?v7 .  ?v4 <http://purl.org/stuff/rev#title> ?v8 .  }
SELECT * WHERE {  <http://db.uwaterloo.ca/~galuc/wsdbm/City93> <http://www.geonames.org/ontology#parentCountry> ?v1 .  ?v2 <http://schema.org/eligibleRegion> ?v1 .  ?v6 <http://schema.org/nationality> ?v1 .  ?v2 <http://purl.org/goodrelations/includes> ?v3 .  ?v2 <http://purl.org/goodrelations/serialNumber> ?v4 .  ?v2 <http://purl.org/goodrelations/validThrough> ?v5 .  ?v2 <http://schema.org/eligibleQuantity> ?v8 .  ?v6 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v7 .  ?v6 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v3 .  ?v9 <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseFor> ?v3 .  }
SELECT * WHERE {  <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre54> <http://ogp.me/ns#tag> ?v1 .  ?v0 <http://ogp.me/ns#tag> ?v1 .  ?v0 <http://schema.org/description> ?v3 .  ?v0 <http://schema.org/expires> ?v4 .  }
SELECT * WHERE {  ?v2 <http://schema.org/eligibleRegion> <http://db.uwaterloo.ca/~galuc/wsdbm/Country23> .  ?v0 <http://purl.org/goodrelations/offers> ?v2 .  ?v2 <http://purl.org/goodrelations/price> ?v3 .  ?v2 <http://purl.org/goodrelations/validFrom> ?v4 .  ?v2 <http://purl.org/goodrelations/validThrough> ?v5 .  ?v0 <http://purl.org/goodrelations/name> ?v1 .  ?v0 <http://schema.org/contactPoint> ?v8 .  ?v0 <http://schema.org/email> ?v10 .  ?v0 <http://schema.org/openingHours> ?v11 .  ?v6 <http://purl.org/stuff/rev#reviewer> ?v8 .  ?v6 <http://purl.org/stuff/rev#rating> ?v7 .  }
SELECT * WHERE {  ?v2 <http://schema.org/eligibleRegion> <http://db.uwaterloo.ca/~galuc/wsdbm/Country21> .  ?v2 <http://purl.org/goodrelations/includes> ?v3 .  ?v0 <http://purl.org/goodrelations/offers> ?v2 .  ?v2 <http://purl.org/goodrelations/validThrough> ?v4 .  ?v2 <http://schema.org/eligibleQuantity> ?v6 .  ?v2 <http://schema.org/priceValidUntil> ?v9 .  ?v0 <http://purl.org/goodrelations/description> ?v1 .  ?v0 <http://schema.org/aggregateRating> ?v5 .  ?v0 <http://schema.org/faxNumber> ?v8 .  ?v0 <http://schema.org/telephone> ?v10 .  }
SELECT * WHERE {  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/gender> <http://db.uwaterloo.ca/~galuc/wsdbm/Gender1> .  ?v0 <http://xmlns.com/foaf/homepage> ?v1 .  ?v0 <http://schema.org/nationality> ?v8 .  ?v2 <http://schema.org/eligibleRegion> ?v8 .  ?v2 <http://purl.org/goodrelations/includes> ?v3 .  ?v4 <http://purl.org/goodrelations/offers> ?v2 .  ?v2 <http://purl.org/goodrelations/serialNumber> ?v5 .  ?v2 <http://purl.org/goodrelations/validThrough> ?v6 .  ?v2 <http://schema.org/eligibleQuantity> ?v7 .  }
SELECT * WHERE {  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre135> .  ?v0 <http://ogp.me/ns#title> ?v1 .  ?v0 <http://schema.org/contentRating> ?v2 .  }
SELECT * WHERE {  <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre111> <http://ogp.me/ns#tag> ?v1 .  ?v0 <http://ogp.me/ns#tag> ?v1 .  ?v0 <http://schema.org/description> ?v3 .  }
SELECT * WHERE {  <http://db.uwaterloo.ca/~galuc/wsdbm/User68180> <http://purl.org/dc/terms/Location> ?v1 .  ?v1 <http://www.geonames.org/ontology#parentCountry> ?v2 .  ?v3 <http://schema.org/eligibleRegion> ?v2 .  ?v3 <http://purl.org/goodrelations/price> ?v4 .  ?v3 <http://purl.org/goodrelations/serialNumber> ?v5 .  ?v3 <http://purl.org/goodrelations/validFrom> ?v6 .  ?v3 <http://purl.org/goodrelations/validThrough> ?v7 .  ?v3 <http://schema.org/eligibleQuantity> ?v8 .  }
SELECT * WHERE {  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/gender> <http://db.uwaterloo.ca/~galuc/wsdbm/Gender1> .  ?v0 <http://purl.org/dc/terms/Location> ?v1 .  ?v0 <http://xmlns.com/foaf/givenName> ?v2 .  ?v0 <http://schema.org/telephone> ?v3 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory3> .  ?v0 <http://ogp.me/ns#tag> ?v1 .  }
SELECT * WHERE {  ?v1 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic38> .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v1 <http://schema.org/description> ?v6 .  ?v0 <http://purl.org/goodrelations/serialNumber> ?v2 .  ?v0 <http://purl.org/goodrelations/validFrom> ?v3 .  ?v0 <http://purl.org/goodrelations/validThrough> ?v4 .  ?v0 <http://schema.org/eligibleQuantity> ?v7 .  ?v0 <http://schema.org/eligibleRegion> ?v8 .  }
SELECT * WHERE {  ?v1 <http://schema.org/eligibleRegion> <http://db.uwaterloo.ca/~galuc/wsdbm/Country19> .  ?v0 <http://purl.org/goodrelations/offers> ?v1 .  ?v1 <http://purl.org/goodrelations/price> ?v2 .  ?v0 <http://schema.org/contactPoint> ?v3 .  ?v0 <http://schema.org/email> ?v5 .  ?v0 <http://schema.org/legalName> ?v6 .  ?v0 <http://schema.org/openingHours> ?v7 .  ?v0 <http://schema.org/paymentAccepted> ?v8 .  }
SELECT * WHERE {  ?v0 <http://purl.org/stuff/rev#hasReview> <http://db.uwaterloo.ca/~galuc/wsdbm/Review2269> .  ?v0 <http://schema.org/keywords> ?v2 .  }
SELECT * WHERE {  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/gender> <http://db.uwaterloo.ca/~galuc/wsdbm/Gender1> .  ?v0 <http://purl.org/dc/terms/Location> ?v1 .  ?v0 <http://schema.org/birthDate> ?v2 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/follows> ?v0 .  }
SELECT * WHERE {  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre105> .  ?v0 <http://schema.org/description> ?v1 .  ?v0 <http://schema.org/editor> ?v2 .  }
SELECT * WHERE {  <http://db.uwaterloo.ca/~galuc/wsdbm/Retailer961> <http://purl.org/goodrelations/offers> ?v0 .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v0 <http://purl.org/goodrelations/price> ?v3 .  ?v0 <http://purl.org/goodrelations/validThrough> ?v4 .  ?v1 <http://schema.org/text> ?v5 .  }
SELECT * WHERE {  ?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/Genre4> .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v3 .  ?v0 <http://xmlns.com/foaf/homepage> ?v1 .  ?v2 <http://purl.org/goodrelations/includes> ?v0 .  ?v0 <http://schema.org/caption> ?v5 .  ?v0 <http://schema.org/contentRating> ?v6 .  ?v0 <http://schema.org/text> ?v7 .  ?v8 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .  }
SELECT * WHERE {  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/gender> <http://db.uwaterloo.ca/~galuc/wsdbm/Gender0> .  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v1 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/follows> ?v0 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/subscribes> ?v3 .  }
SELECT * WHERE {  <http://db.uwaterloo.ca/~galuc/wsdbm/City119> <http://www.geonames.org/ontology#parentCountry> ?v1 .  ?v2 <http://schema.org/eligibleRegion> ?v1 .  ?v2 <http://purl.org/goodrelations/validFrom> ?v3 .  }
SELECT * WHERE {  ?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/Genre9> .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v3 .  ?v0 <http://xmlns.com/foaf/homepage> ?v1 .  ?v2 <http://purl.org/goodrelations/includes> ?v0 .  ?v0 <http://schema.org/caption> ?v5 .  ?v0 <http://schema.org/contentRating> ?v6 .  ?v0 <http://schema.org/text> ?v7 .  ?v8 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .  }
SELECT * WHERE {  ?v2 <http://schema.org/eligibleRegion> <http://db.uwaterloo.ca/~galuc/wsdbm/Country11> .  ?v0 <http://purl.org/goodrelations/offers> ?v2 .  ?v2 <http://purl.org/goodrelations/price> ?v3 .  ?v2 <http://purl.org/goodrelations/validFrom> ?v4 .  ?v2 <http://purl.org/goodrelations/validThrough> ?v5 .  ?v0 <http://purl.org/goodrelations/name> ?v1 .  ?v0 <http://schema.org/contactPoint> ?v8 .  ?v0 <http://schema.org/email> ?v10 .  ?v0 <http://schema.org/openingHours> ?v11 .  ?v6 <http://purl.org/stuff/rev#reviewer> ?v8 .  ?v6 <http://purl.org/stuff/rev#rating> ?v7 .  }
SELECT * WHERE {  ?v1 <http://schema.org/eligibleRegion> <http://db.uwaterloo.ca/~galuc/wsdbm/Country2> .  ?v0 <http://purl.org/goodrelations/offers> ?v1 .  ?v1 <http://purl.org/goodrelations/price> ?v2 .  ?v1 <http://schema.org/priceValidUntil> ?v4 .  }
SELECT * WHERE {  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/gender> <http://db.uwaterloo.ca/~galuc/wsdbm/Gender1> .  ?v0 <http://xmlns.com/foaf/homepage> ?v1 .  ?v0 <http://schema.org/nationality> ?v8 .  ?v2 <http://schema.org/eligibleRegion> ?v8 .  ?v2 <http://purl.org/goodrelations/includes> ?v3 .  ?v4 <http://purl.org/goodrelations/offers> ?v2 .  ?v2 <http://purl.org/goodrelations/serialNumber> ?v5 .  ?v2 <http://purl.org/goodrelations/validThrough> ?v6 .  ?v2 <http://schema.org/eligibleQuantity> ?v7 .  }
SELECT * WHERE {  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/gender> <http://db.uwaterloo.ca/~galuc/wsdbm/Gender1> .  ?v0 <http://xmlns.com/foaf/age> ?v1 .  ?v0 <http://xmlns.com/foaf/familyName> ?v2 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/follows> ?v0 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/subscribes> ?v4 .  }
SELECT * WHERE {  ?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic123> .  ?v0 <http://ogp.me/ns#title> ?v2 .  ?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .  }
SELECT * WHERE {  ?v0 <http://xmlns.com/foaf/age> <http://db.uwaterloo.ca/~galuc/wsdbm/AgeGroup8> .  ?v2 <http://schema.org/author> ?v0 .  ?v0 <http://schema.org/telephone> ?v3 .  }
SELECT * WHERE {  <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre119> <http://ogp.me/ns#tag> ?v1 .  ?v0 <http://ogp.me/ns#tag> ?v1 .  ?v0 <http://schema.org/description> ?v3 .  ?v0 <http://schema.org/expires> ?v4 .  }
SELECT * WHERE {  ?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language19> .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v1 <http://ogp.me/ns#title> ?v2 .  }
SELECT * WHERE {  ?v2 <http://purl.org/stuff/rev#hasReview> <http://db.uwaterloo.ca/~galuc/wsdbm/Review130565> .  ?v2 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v2 .  ?v0 <http://xmlns.com/foaf/age> ?v1 .  }
SELECT * WHERE {  ?v1 <http://schema.org/eligibleRegion> <http://db.uwaterloo.ca/~galuc/wsdbm/Country24> .  ?v0 <http://purl.org/goodrelations/offers> ?v1 .  ?v1 <http://purl.org/goodrelations/price> ?v2 .  ?v0 <http://schema.org/contactPoint> ?v3 .  ?v0 <http://schema.org/email> ?v5 .  ?v0 <http://schema.org/legalName> ?v6 .  ?v0 <http://schema.org/openingHours> ?v7 .  ?v0 <http://schema.org/paymentAccepted> ?v8 .  }
SELECT * WHERE {  <http://db.uwaterloo.ca/~galuc/wsdbm/Purchase72880> <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseFor> ?v0 .  ?v0 <http://ogp.me/ns#tag> ?v1 .  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .  ?v0 <http://schema.org/text> ?v4 .  ?v2 <http://ogp.me/ns#tag> ?v1 .  }
SELECT * WHERE {  <http://db.uwaterloo.ca/~galuc/wsdbm/Purchase33337> <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseFor> ?v0 .  ?v0 <http://ogp.me/ns#tag> ?v1 .  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .  ?v0 <http://schema.org/text> ?v4 .  ?v2 <http://ogp.me/ns#tag> ?v1 .  }
SELECT * WHERE {  <http://db.uwaterloo.ca/~galuc/wsdbm/City91> <http://www.geonames.org/ontology#parentCountry> ?v1 .  ?v2 <http://schema.org/eligibleRegion> ?v1 .  ?v6 <http://schema.org/nationality> ?v1 .  ?v2 <http://purl.org/goodrelations/includes> ?v3 .  ?v2 <http://purl.org/goodrelations/serialNumber> ?v4 .  ?v2 <http://purl.org/goodrelations/validThrough> ?v5 .  ?v2 <http://schema.org/eligibleQuantity> ?v8 .  ?v6 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v7 .  ?v6 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v3 .  ?v9 <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseFor> ?v3 .  }
SELECT * WHERE {  <http://db.uwaterloo.ca/~galuc/wsdbm/Purchase114762> <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseFor> ?v0 .  ?v0 <http://ogp.me/ns#title> ?v1 .  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .  ?v0 <http://schema.org/description> ?v3 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v4 .  }
SELECT * WHERE {  <http://db.uwaterloo.ca/~galuc/wsdbm/City75> <http://www.geonames.org/ontology#parentCountry> ?v1 .  ?v2 <http://schema.org/eligibleRegion> ?v1 .  ?v4 <http://schema.org/nationality> ?v1 .  ?v2 <http://schema.org/eligibleQuantity> ?v3 .  }
SELECT * WHERE {  ?v0 <http://schema.org/eligibleRegion> <http://db.uwaterloo.ca/~galuc/wsdbm/Country14> .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v2 <http://purl.org/goodrelations/offers> ?v0 .  ?v0 <http://purl.org/goodrelations/price> ?v3 .  ?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .  ?v0 <http://purl.org/goodrelations/validFrom> ?v5 .  ?v0 <http://purl.org/goodrelations/validThrough> ?v6 .  ?v0 <http://schema.org/eligibleQuantity> ?v8 .  ?v0 <http://schema.org/priceValidUntil> ?v10 .  ?v1 <http://schema.org/author> ?v7 .  }
SELECT * WHERE {  ?v5 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/Role2> .  ?v7 <http://purl.org/stuff/rev#reviewer> ?v5 .  ?v5 <http://db.uwaterloo.ca/~galuc/wsdbm/follows> ?v5 .  ?v0 <http://purl.org/stuff/rev#hasReview> ?v7 .  ?v0 <http://xmlns.com/foaf/homepage> ?v1 .  ?v2 <http://purl.org/goodrelations/includes> ?v0 .  ?v0 <http://ogp.me/ns#title> ?v3 .  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v4 .  ?v0 <http://schema.org/description> ?v8 .  ?v0 <http://schema.org/text> ?v10 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v11 .  ?v2 <http://schema.org/eligibleRegion> ?v9 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory4> .  ?v0 <http://schema.org/contentRating> ?v2 .  ?v0 <http://schema.org/description> ?v3 .  ?v0 <http://schema.org/expires> ?v4 .  ?v0 <http://schema.org/text> ?v5 .  }
SELECT * WHERE {  <http://db.uwaterloo.ca/~galuc/wsdbm/City197> <http://www.geonames.org/ontology#parentCountry> ?v1 .  ?v4 <http://schema.org/eligibleRegion> ?v1 .  ?v9 <http://schema.org/nationality> ?v1 .  ?v2 <http://purl.org/goodrelations/offers> ?v4 .  ?v4 <http://purl.org/goodrelations/serialNumber> ?v5 .  ?v4 <http://schema.org/eligibleQuantity> ?v7 .  ?v4 <http://schema.org/priceValidUntil> ?v10 .  ?v2 <http://purl.org/goodrelations/description> ?v3 .  ?v2 <http://schema.org/aggregateRating> ?v6 .  ?v2 <http://schema.org/legalName> ?v8 .  }
SELECT * WHERE {  ?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic162> .  ?v0 <http://purl.org/stuff/rev#hasReview> ?v2 .  ?v0 <http://schema.org/contentRating> ?v8 .  ?v2 <http://purl.org/stuff/rev#rating> ?v3 .  ?v2 <http://purl.org/stuff/rev#reviewer> ?v4 .  ?v2 <http://purl.org/stuff/rev#text> ?v5 .  ?v2 <http://purl.org/stuff/rev#title> ?v6 .  ?v2 <http://purl.org/stuff/rev#totalVotes> ?v7 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory9> .  ?v0 <http://xmlns.com/foaf/homepage> ?v1 .  ?v0 <http://schema.org/expires> ?v3 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/Role2> .  ?v0 <http://schema.org/birthDate> ?v2 .  ?v0 <http://schema.org/jobTitle> ?v3 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v4 .  }
SELECT * WHERE {  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/gender> <http://db.uwaterloo.ca/~galuc/wsdbm/Gender1> .  ?v0 <http://xmlns.com/foaf/age> ?v1 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory13> .  ?v0 <http://ogp.me/ns#title> ?v1 .  ?v0 <http://schema.org/caption> ?v3 .  ?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .  }
SELECT * WHERE {  ?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic206> .  ?v0 <http://xmlns.com/foaf/homepage> ?v1 .  ?v0 <http://ogp.me/ns#title> ?v3 .  ?v0 <http://schema.org/expires> ?v4 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v5 .  ?v6 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .  ?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseFor> ?v0 .  }
SELECT * WHERE {  <http://db.uwaterloo.ca/~galuc/wsdbm/Offer51690> <http://purl.org/goodrelations/includes> ?v1 .  ?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .  ?v1 <http://schema.org/keywords> ?v3 .  }
SELECT * WHERE {  ?v0 <http://purl.org/dc/terms/Location> <http://db.uwaterloo.ca/~galuc/wsdbm/City155> .  ?v0 <http://xmlns.com/foaf/familyName> ?v2 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/userId> ?v3 .  }
SELECT * WHERE {  <http://db.uwaterloo.ca/~galuc/wsdbm/Retailer219> <http://purl.org/goodrelations/offers> ?v0 .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v0 <http://purl.org/goodrelations/price> ?v3 .  ?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .  ?v0 <http://schema.org/eligibleQuantity> ?v5 .  ?v0 <http://schema.org/eligibleRegion> ?v6 .  ?v0 <http://schema.org/priceValidUntil> ?v7 .  }
SELECT * WHERE {  ?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre40> .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v1 <http://schema.org/contentSize> ?v2 .  ?v1 <http://schema.org/description> ?v3 .  }
SELECT * WHERE {  <http://db.uwaterloo.ca/~galuc/wsdbm/User36871> <http://xmlns.com/foaf/age> ?v1 .  }
SELECT * WHERE {  ?v0 <http://schema.org/eligibleRegion> <http://db.uwaterloo.ca/~galuc/wsdbm/Country7> .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v2 <http://purl.org/goodrelations/offers> ?v0 .  ?v0 <http://purl.org/goodrelations/price> ?v3 .  ?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .  ?v0 <http://purl.org/goodrelations/validFrom> ?v5 .  ?v0 <http://purl.org/goodrelations/validThrough> ?v6 .  ?v0 <http://schema.org/eligibleQuantity> ?v8 .  ?v0 <http://schema.org/priceValidUntil> ?v11 .  ?v1 <http://ogp.me/ns#tag> ?v7 .  ?v1 <http://schema.org/keywords> ?v10 .  ?v12 <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseFor> ?v1 .  }
SELECT * WHERE {  ?v0 <http://purl.org/stuff/rev#hasReview> <http://db.uwaterloo.ca/~galuc/wsdbm/Review118608> .  ?v0 <http://schema.org/keywords> ?v2 .  }
SELECT * WHERE {  ?v0 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language34> .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v2 .  }
SELECT * WHERE {  ?v0 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language22> .  ?v0 <http://purl.org/stuff/rev#hasReview> ?v1 .  ?v1 <http://purl.org/stuff/rev#title> ?v2 .  }
SELECT * WHERE {  ?v1 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language16> .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v1 <http://ogp.me/ns#title> ?v2 .  }
SELECT * WHERE {  <http://db.uwaterloo.ca/~galuc/wsdbm/Purchase19426> <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseFor> ?v0 .  ?v0 <http://ogp.me/ns#tag> ?v1 .  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .  ?v0 <http://schema.org/text> ?v4 .  ?v2 <http://ogp.me/ns#tag> ?v1 .  }
SELECT * WHERE {  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/gender> <http://db.uwaterloo.ca/~galuc/wsdbm/Gender1> .  ?v0 <http://purl.org/dc/terms/Location> ?v1 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/follows> ?v0 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/userId> ?v5 .  ?v1 <http://www.geonames.org/ontology#parentCountry> ?v2 .  ?v3 <http://purl.org/ontology/mo/performed_in> ?v1 .  }
SELECT * WHERE {  ?v0 <http://schema.org/eligibleRegion> <http://db.uwaterloo.ca/~galuc/wsdbm/Country3> .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v2 <http://purl.org/goodrelations/offers> ?v0 .  ?v0 <http://purl.org/goodrelations/validFrom> ?v3 .  ?v0 <http://purl.org/goodrelations/validThrough> ?v4 .  ?v0 <http://schema.org/eligibleQuantity> ?v5 .  ?v0 <http://schema.org/priceValidUntil> ?v7 .  }
SELECT * WHERE {  <http://db.uwaterloo.ca/~galuc/wsdbm/User85041> <http://schema.org/nationality> ?v2 .  ?v0 <http://schema.org/eligibleRegion> ?v2 .  ?v0 <http://schema.org/eligibleQuantity> ?v1 .  }
SELECT * WHERE {  ?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic116> .  ?v0 <http://schema.org/keywords> ?v2 .  ?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseFor> ?v0 .  ?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/makesPurchase> ?v4 .  ?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseDate> ?v5 .  }
SELECT * WHERE {  ?v0 <http://purl.org/dc/terms/Location> <http://db.uwaterloo.ca/~galuc/wsdbm/City136> .  ?v0 <http://xmlns.com/foaf/age> ?v2 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v3 .  ?v3 <http://ogp.me/ns#title> ?v4 .  ?v3 <http://schema.org/keywords> ?v5 .  }
SELECT * WHERE {  ?v0 <http://purl.org/dc/terms/Location> <http://db.uwaterloo.ca/~galuc/wsdbm/City52> .  ?v0 <http://xmlns.com/foaf/age> ?v2 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v3 .  ?v3 <http://ogp.me/ns#title> ?v4 .  ?v3 <http://schema.org/keywords> ?v5 .  }
SELECT * WHERE {  ?v0 <http://purl.org/dc/terms/Location> <http://db.uwaterloo.ca/~galuc/wsdbm/City106> .  ?v0 <http://xmlns.com/foaf/age> ?v2 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v3 .  ?v3 <http://ogp.me/ns#title> ?v4 .  ?v3 <http://schema.org/keywords> ?v5 .  }
SELECT * WHERE {  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre88> .  ?v0 <http://ogp.me/ns#title> ?v1 .  }
SELECT * WHERE {  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre31> .  ?v0 <http://xmlns.com/foaf/homepage> ?v1 .  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .  ?v0 <http://schema.org/description> ?v3 .  ?v0 <http://schema.org/expires> ?v4 .  ?v1 <http://schema.org/url> ?v5 .  }
SELECT * WHERE {  <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre83> <http://ogp.me/ns#tag> ?v1 .  ?v0 <http://ogp.me/ns#tag> ?v1 .  ?v0 <http://schema.org/description> ?v3 .  }
SELECT * WHERE {  ?v0 <http://xmlns.com/foaf/age> <http://db.uwaterloo.ca/~galuc/wsdbm/AgeGroup3> .  ?v2 <http://schema.org/author> ?v0 .  ?v0 <http://schema.org/telephone> ?v3 .  }
SELECT * WHERE {  ?v1 <http://schema.org/eligibleRegion> <http://db.uwaterloo.ca/~galuc/wsdbm/Country6> .  ?v0 <http://purl.org/goodrelations/offers> ?v1 .  ?v1 <http://purl.org/goodrelations/price> ?v2 .  ?v1 <http://schema.org/priceValidUntil> ?v4 .  }
SELECT * WHERE {  <http://db.uwaterloo.ca/~galuc/wsdbm/User65011> <http://purl.org/dc/terms/Location> ?v1 .  ?v1 <http://www.geonames.org/ontology#parentCountry> ?v2 .  ?v3 <http://schema.org/eligibleRegion> ?v2 .  ?v3 <http://schema.org/eligibleQuantity> ?v4 .  ?v3 <http://schema.org/priceValidUntil> ?v5 .  }
SELECT * WHERE {  ?v0 <http://purl.org/dc/terms/Location> <http://db.uwaterloo.ca/~galuc/wsdbm/City109> .  ?v0 <http://xmlns.com/foaf/homepage> ?v2 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/userId> ?v3 .  }
SELECT * WHERE {  ?v0 <http://purl.org/stuff/rev#hasReview> <http://db.uwaterloo.ca/~galuc/wsdbm/Review142158> .  ?v0 <http://schema.org/keywords> ?v2 .  }
SELECT * WHERE {  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/gender> <http://db.uwaterloo.ca/~galuc/wsdbm/Gender1> .  ?v0 <http://purl.org/dc/terms/Location> ?v1 .  ?v0 <http://schema.org/birthDate> ?v2 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/follows> ?v0 .  }
SELECT * WHERE {  ?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic227> .  ?v0 <http://purl.org/stuff/rev#hasReview> ?v2 .  ?v2 <http://purl.org/stuff/rev#text> ?v3 .  ?v2 <http://purl.org/stuff/rev#title> ?v4 .  ?v2 <http://purl.org/stuff/rev#totalVotes> ?v5 .  }
SELECT * WHERE {  <http://db.uwaterloo.ca/~galuc/wsdbm/Retailer663> <http://purl.org/goodrelations/offers> ?v0 .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v0 <http://purl.org/goodrelations/serialNumber> ?v3 .  ?v0 <http://purl.org/goodrelations/validThrough> ?v4 .  ?v0 <http://schema.org/eligibleQuantity> ?v5 .  ?v0 <http://schema.org/priceValidUntil> ?v6 .  }
SELECT * WHERE {  <http://db.uwaterloo.ca/~galuc/wsdbm/Retailer1162> <http://purl.org/goodrelations/offers> ?v1 .  ?v1 <http://purl.org/goodrelations/price> ?v2 .  ?v1 <http://purl.org/goodrelations/serialNumber> ?v3 .  ?v1 <http://schema.org/eligibleRegion> ?v4 .  }
SELECT * WHERE {  ?v1 <http://schema.org/eligibleRegion> <http://db.uwaterloo.ca/~galuc/wsdbm/Country21> .  ?v0 <http://purl.org/goodrelations/offers> ?v1 .  ?v1 <http://purl.org/goodrelations/price> ?v2 .  ?v0 <http://schema.org/contactPoint> ?v3 .  ?v0 <http://schema.org/email> ?v5 .  ?v0 <http://schema.org/legalName> ?v6 .  ?v0 <http://schema.org/openingHours> ?v7 .  ?v0 <http://schema.org/paymentAccepted> ?v8 .  }
SELECT * WHERE {  <http://db.uwaterloo.ca/~galuc/wsdbm/Retailer203> <http://purl.org/goodrelations/offers> ?v0 .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v0 <http://purl.org/goodrelations/serialNumber> ?v3 .  ?v0 <http://purl.org/goodrelations/validThrough> ?v4 .  ?v0 <http://schema.org/eligibleQuantity> ?v5 .  ?v0 <http://schema.org/priceValidUntil> ?v6 .  }
SELECT * WHERE {  <http://db.uwaterloo.ca/~galuc/wsdbm/User47091> <http://purl.org/dc/terms/Location> ?v1 .  ?v1 <http://www.geonames.org/ontology#parentCountry> ?v2 .  ?v3 <http://schema.org/eligibleRegion> ?v2 .  ?v3 <http://schema.org/eligibleQuantity> ?v4 .  ?v3 <http://schema.org/priceValidUntil> ?v5 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/Role2> .  ?v0 <http://schema.org/email> ?v2 .  ?v0 <http://schema.org/nationality> ?v3 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/gender> ?v4 .  }
SELECT * WHERE {  ?v1 <http://www.geonames.org/ontology#parentCountry> <http://db.uwaterloo.ca/~galuc/wsdbm/Country9> .  ?v0 <http://purl.org/dc/terms/Location> ?v1 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/gender> ?v3 .  }
SELECT * WHERE {  ?v0 <http://schema.org/eligibleRegion> <http://db.uwaterloo.ca/~galuc/wsdbm/Country6> .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v2 <http://purl.org/goodrelations/offers> ?v0 .  ?v0 <http://purl.org/goodrelations/price> ?v3 .  ?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .  ?v0 <http://purl.org/goodrelations/validFrom> ?v5 .  ?v0 <http://purl.org/goodrelations/validThrough> ?v6 .  ?v0 <http://schema.org/eligibleQuantity> ?v8 .  ?v0 <http://schema.org/priceValidUntil> ?v10 .  ?v1 <http://schema.org/author> ?v7 .  }
SELECT * WHERE {  <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre134> <http://ogp.me/ns#tag> ?v2 .  ?v0 <http://ogp.me/ns#tag> ?v2 .  ?v0 <http://xmlns.com/foaf/homepage> ?v1 .  ?v0 <http://schema.org/contentRating> ?v4 .  ?v5 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .  }
SELECT * WHERE {  <http://db.uwaterloo.ca/~galuc/wsdbm/User69832> <http://xmlns.com/foaf/age> ?v1 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory5> .  ?v0 <http://ogp.me/ns#tag> ?v1 .  }
SELECT * WHERE {  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/gender> <http://db.uwaterloo.ca/~galuc/wsdbm/Gender0> .  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v1 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/follows> ?v0 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/subscribes> ?v3 .  }
SELECT * WHERE {  <http://db.uwaterloo.ca/~galuc/wsdbm/Offer13219> <http://purl.org/goodrelations/includes> ?v1 .  ?v1 <http://schema.org/description> ?v2 .  ?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v1 .  ?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/gender> ?v4 .  }
SELECT * WHERE {  <http://db.uwaterloo.ca/~galuc/wsdbm/Purchase3365> <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseFor> ?v3 .  ?v2 <http://purl.org/goodrelations/includes> ?v3 .  ?v2 <http://purl.org/goodrelations/validThrough> ?v4 .  ?v2 <http://schema.org/eligibleQuantity> ?v5 .  ?v2 <http://schema.org/eligibleRegion> ?v1 .  ?v0 <http://www.geonames.org/ontology#parentCountry> ?v1 .  ?v6 <http://schema.org/nationality> ?v1 .  }
SELECT * WHERE {  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/gender> <http://db.uwaterloo.ca/~galuc/wsdbm/Gender0> .  ?v0 <http://purl.org/dc/terms/Location> ?v1 .  ?v0 <http://schema.org/birthDate> ?v2 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/friendOf> ?v0 .  }
SELECT * WHERE {  ?v0 <http://schema.org/nationality> <http://db.uwaterloo.ca/~galuc/wsdbm/Country14> .  ?v0 <http://xmlns.com/foaf/familyName> ?v1 .  ?v0 <http://schema.org/birthDate> ?v2 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/gender> ?v4 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v5 .  }
SELECT * WHERE {  ?v0 <http://schema.org/nationality> <http://db.uwaterloo.ca/~galuc/wsdbm/Country16> .  ?v0 <http://xmlns.com/foaf/familyName> ?v1 .  ?v0 <http://schema.org/birthDate> ?v2 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/gender> ?v4 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v5 .  }
SELECT * WHERE {  ?v0 <http://schema.org/eligibleRegion> <http://db.uwaterloo.ca/~galuc/wsdbm/Country4> .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v0 <http://purl.org/goodrelations/price> ?v2 .  ?v0 <http://purl.org/goodrelations/validThrough> ?v3 .  ?v0 <http://schema.org/eligibleQuantity> ?v4 .  ?v1 <http://schema.org/text> ?v6 .  }
SELECT * WHERE {  <http://db.uwaterloo.ca/~galuc/wsdbm/Retailer611> <http://purl.org/goodrelations/offers> ?v0 .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v0 <http://purl.org/goodrelations/serialNumber> ?v3 .  ?v0 <http://purl.org/goodrelations/validThrough> ?v4 .  ?v0 <http://schema.org/eligibleQuantity> ?v5 .  ?v0 <http://schema.org/priceValidUntil> ?v6 .  }
SELECT * WHERE {  ?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/gender> <http://db.uwaterloo.ca/~galuc/wsdbm/Gender1> .  ?v2 <http://schema.org/jobTitle> ?v3 .  ?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/makesPurchase> ?v0 .  ?v0 <http://purl.org/goodrelations/price> ?v1 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseDate> ?v5 .  }
SELECT * WHERE {  ?v0 <http://schema.org/eligibleRegion> <http://db.uwaterloo.ca/~galuc/wsdbm/Country10> .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v2 <http://purl.org/goodrelations/offers> ?v0 .  ?v0 <http://purl.org/goodrelations/validFrom> ?v3 .  ?v0 <http://purl.org/goodrelations/validThrough> ?v4 .  ?v0 <http://schema.org/eligibleQuantity> ?v5 .  ?v0 <http://schema.org/priceValidUntil> ?v7 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/Role2> .  ?v2 <http://schema.org/contactPoint> ?v0 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/gender> ?v3 .  }
SELECT * WHERE {  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/gender> <http://db.uwaterloo.ca/~galuc/wsdbm/Gender1> .  ?v0 <http://purl.org/dc/terms/Location> ?v1 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/follows> ?v0 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/userId> ?v5 .  ?v1 <http://www.geonames.org/ontology#parentCountry> ?v2 .  ?v3 <http://purl.org/ontology/mo/performed_in> ?v1 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory7> .  ?v0 <http://ogp.me/ns#tag> ?v1 .  ?v0 <http://schema.org/contentRating> ?v5 .  ?v0 <http://schema.org/contentSize> ?v6 .  ?v0 <http://schema.org/description> ?v7 .  ?v8 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .  ?v2 <http://ogp.me/ns#tag> ?v1 .  ?v2 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v4 .  }
SELECT * WHERE {  ?v0 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language5> .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v2 .  }
SELECT * WHERE {  ?v0 <http://schema.org/nationality> <http://db.uwaterloo.ca/~galuc/wsdbm/Country16> .  ?v0 <http://xmlns.com/foaf/familyName> ?v1 .  ?v0 <http://schema.org/birthDate> ?v2 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/gender> ?v4 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v5 .  }
SELECT * WHERE {  ?v1 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic134> .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v1 <http://schema.org/description> ?v6 .  ?v0 <http://purl.org/goodrelations/serialNumber> ?v2 .  ?v0 <http://purl.org/goodrelations/validFrom> ?v3 .  ?v0 <http://purl.org/goodrelations/validThrough> ?v4 .  ?v0 <http://schema.org/eligibleQuantity> ?v7 .  ?v0 <http://schema.org/eligibleRegion> ?v8 .  }
SELECT * WHERE {  <http://db.uwaterloo.ca/~galuc/wsdbm/Retailer859> <http://purl.org/goodrelations/offers> ?v0 .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v0 <http://purl.org/goodrelations/serialNumber> ?v3 .  ?v0 <http://purl.org/goodrelations/validThrough> ?v4 .  ?v0 <http://schema.org/eligibleQuantity> ?v5 .  ?v0 <http://schema.org/priceValidUntil> ?v6 .  }
SELECT * WHERE {  ?v1 <http://www.geonames.org/ontology#parentCountry> <http://db.uwaterloo.ca/~galuc/wsdbm/Country17> .  ?v0 <http://purl.org/dc/terms/Location> ?v1 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/gender> ?v3 .  }
SELECT * WHERE {  <http://db.uwaterloo.ca/~galuc/wsdbm/User27060> <http://xmlns.com/foaf/age> ?v1 .  }
SELECT * WHERE {  <http://db.uwaterloo.ca/~galuc/wsdbm/User27915> <http://purl.org/dc/terms/Location> ?v1 .  ?v1 <http://www.geonames.org/ontology#parentCountry> ?v2 .  ?v3 <http://schema.org/eligibleRegion> ?v2 .  ?v3 <http://schema.org/eligibleQuantity> ?v4 .  ?v3 <http://schema.org/priceValidUntil> ?v5 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/Role2> .  ?v2 <http://schema.org/contactPoint> ?v0 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/gender> ?v3 .  }
SELECT * WHERE {  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/gender> <http://db.uwaterloo.ca/~galuc/wsdbm/Gender1> .  ?v0 <http://xmlns.com/foaf/givenName> ?v1 .  ?v0 <http://schema.org/nationality> ?v3 .  ?v2 <http://www.geonames.org/ontology#parentCountry> ?v3 .  ?v4 <http://schema.org/eligibleRegion> ?v3 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/Role2> .  ?v2 <http://schema.org/contactPoint> ?v0 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/gender> ?v3 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory11> .  ?v0 <http://ogp.me/ns#tag> ?v1 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v3 .  }
SELECT * WHERE {  <http://db.uwaterloo.ca/~galuc/wsdbm/User79183> <http://schema.org/nationality> ?v3 .  ?v0 <http://schema.org/eligibleRegion> ?v3 .  ?v0 <http://purl.org/goodrelations/serialNumber> ?v1 .  ?v0 <http://purl.org/goodrelations/validThrough> ?v2 .  }
SELECT * WHERE {  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/gender> <http://db.uwaterloo.ca/~galuc/wsdbm/Gender0> .  ?v0 <http://purl.org/dc/terms/Location> ?v1 .  ?v0 <http://schema.org/birthDate> ?v2 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/friendOf> ?v0 .  }
SELECT * WHERE {  <http://db.uwaterloo.ca/~galuc/wsdbm/Retailer163> <http://purl.org/goodrelations/offers> ?v0 .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v0 <http://purl.org/goodrelations/price> ?v3 .  ?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .  ?v0 <http://schema.org/eligibleQuantity> ?v5 .  ?v0 <http://schema.org/eligibleRegion> ?v6 .  ?v0 <http://schema.org/priceValidUntil> ?v7 .  }
SELECT * WHERE {  ?v1 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic73> .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v1 <http://schema.org/description> ?v6 .  ?v0 <http://purl.org/goodrelations/serialNumber> ?v2 .  ?v0 <http://purl.org/goodrelations/validFrom> ?v3 .  ?v0 <http://purl.org/goodrelations/validThrough> ?v4 .  ?v0 <http://schema.org/eligibleQuantity> ?v7 .  ?v0 <http://schema.org/eligibleRegion> ?v8 .  }
SELECT * WHERE {  ?v5 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/Role1> .  ?v1 <http://schema.org/editor> ?v5 .  ?v5 <http://db.uwaterloo.ca/~galuc/wsdbm/gender> ?v8 .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v1 <http://ogp.me/ns#title> ?v4 .  ?v1 <http://schema.org/expires> ?v7 .  ?v0 <http://purl.org/goodrelations/serialNumber> ?v2 .  ?v0 <http://purl.org/goodrelations/validFrom> ?v3 .  }
SELECT * WHERE {  ?v0 <http://purl.org/dc/terms/Location> <http://db.uwaterloo.ca/~galuc/wsdbm/City212> .  ?v0 <http://xmlns.com/foaf/age> ?v2 .  ?v0 <http://schema.org/birthDate> ?v3 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/Role2> .  ?v0 <http://xmlns.com/foaf/age> ?v1 .  ?v0 <http://xmlns.com/foaf/givenName> ?v2 .  ?v4 <http://schema.org/editor> ?v0 .  }
SELECT * WHERE {  ?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre81> .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v1 <http://schema.org/contentSize> ?v2 .  ?v1 <http://schema.org/description> ?v3 .  }
SELECT * WHERE {  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/gender> <http://db.uwaterloo.ca/~galuc/wsdbm/Gender1> .  ?v0 <http://purl.org/dc/terms/Location> ?v1 .  ?v0 <http://xmlns.com/foaf/givenName> ?v2 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/userId> ?v4 .  }
SELECT * WHERE {  ?v2 <http://schema.org/eligibleRegion> <http://db.uwaterloo.ca/~galuc/wsdbm/Country14> .  ?v2 <http://purl.org/goodrelations/includes> ?v3 .  ?v0 <http://purl.org/goodrelations/offers> ?v2 .  ?v2 <http://purl.org/goodrelations/validThrough> ?v4 .  ?v2 <http://schema.org/eligibleQuantity> ?v6 .  ?v2 <http://schema.org/priceValidUntil> ?v9 .  ?v0 <http://purl.org/goodrelations/description> ?v1 .  ?v0 <http://schema.org/aggregateRating> ?v5 .  ?v0 <http://schema.org/faxNumber> ?v8 .  ?v0 <http://schema.org/telephone> ?v10 .  }
SELECT * WHERE {  ?v0 <http://xmlns.com/foaf/age> <http://db.uwaterloo.ca/~galuc/wsdbm/AgeGroup7> .  ?v0 <http://xmlns.com/foaf/givenName> ?v2 .  ?v0 <http://schema.org/email> ?v3 .  ?v0 <http://schema.org/telephone> ?v4 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/subscribes> ?v5 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/userId> ?v6 .  }
SELECT * WHERE {  <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre77> <http://ogp.me/ns#tag> ?v2 .  ?v0 <http://ogp.me/ns#tag> ?v2 .  ?v0 <http://xmlns.com/foaf/homepage> ?v1 .  ?v0 <http://schema.org/contentRating> ?v4 .  ?v5 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .  }
SELECT * WHERE {  <http://db.uwaterloo.ca/~galuc/wsdbm/User41079> <http://schema.org/nationality> ?v2 .  ?v0 <http://schema.org/eligibleRegion> ?v2 .  ?v0 <http://schema.org/eligibleQuantity> ?v1 .  }
SELECT * WHERE {  ?v1 <http://schema.org/eligibleRegion> <http://db.uwaterloo.ca/~galuc/wsdbm/Country11> .  ?v0 <http://purl.org/goodrelations/offers> ?v1 .  ?v1 <http://purl.org/goodrelations/price> ?v2 .  ?v0 <http://schema.org/contactPoint> ?v3 .  ?v0 <http://schema.org/email> ?v5 .  ?v0 <http://schema.org/legalName> ?v6 .  ?v0 <http://schema.org/openingHours> ?v7 .  ?v0 <http://schema.org/paymentAccepted> ?v8 .  }
SELECT * WHERE {  ?v0 <http://purl.org/goodrelations/includes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product10994> .  ?v0 <http://purl.org/goodrelations/price> ?v2 .  ?v0 <http://schema.org/eligibleQuantity> ?v3 .  ?v0 <http://schema.org/priceValidUntil> ?v4 .  }
SELECT * WHERE {  ?v0 <http://xmlns.com/foaf/age> <http://db.uwaterloo.ca/~galuc/wsdbm/AgeGroup6> .  ?v0 <http://xmlns.com/foaf/givenName> ?v2 .  ?v0 <http://schema.org/email> ?v3 .  ?v0 <http://schema.org/telephone> ?v4 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/subscribes> ?v5 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/userId> ?v6 .  }
SELECT * WHERE {  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/gender> <http://db.uwaterloo.ca/~galuc/wsdbm/Gender1> .  ?v0 <http://xmlns.com/foaf/givenName> ?v1 .  ?v0 <http://schema.org/nationality> ?v3 .  ?v2 <http://www.geonames.org/ontology#parentCountry> ?v3 .  ?v4 <http://schema.org/eligibleRegion> ?v3 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/Role1> .  ?v2 <http://schema.org/contactPoint> ?v0 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/gender> ?v3 .  }
SELECT * WHERE {  <http://db.uwaterloo.ca/~galuc/wsdbm/Retailer217> <http://purl.org/goodrelations/offers> ?v1 .  ?v1 <http://purl.org/goodrelations/price> ?v2 .  ?v1 <http://purl.org/goodrelations/serialNumber> ?v3 .  ?v1 <http://schema.org/eligibleRegion> ?v4 .  }
SELECT * WHERE {  <http://db.uwaterloo.ca/~galuc/wsdbm/User74461> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v1 .  }
SELECT * WHERE {  ?v4 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic140> .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v4 .  ?v0 <http://xmlns.com/foaf/age> ?v1 .  ?v0 <http://xmlns.com/foaf/familyName> ?v2 .  ?v0 <http://xmlns.com/foaf/homepage> ?v3 .  }
SELECT * WHERE {  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre83> .  ?v0 <http://xmlns.com/foaf/homepage> ?v1 .  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .  ?v0 <http://schema.org/description> ?v3 .  ?v0 <http://schema.org/expires> ?v4 .  ?v1 <http://schema.org/url> ?v5 .  }
SELECT * WHERE {  ?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory0> .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v1 <http://ogp.me/ns#tag> ?v2 .  ?v1 <http://ogp.me/ns#title> ?v4 .  ?v1 <http://schema.org/expires> ?v7 .  ?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v3 .  ?v3 <http://ogp.me/ns#tag> ?v2 .  ?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .  }
SELECT * WHERE {  ?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic127> .  ?v0 <http://purl.org/stuff/rev#hasReview> ?v2 .  ?v2 <http://purl.org/stuff/rev#text> ?v3 .  ?v2 <http://purl.org/stuff/rev#title> ?v4 .  ?v2 <http://purl.org/stuff/rev#totalVotes> ?v5 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/Role2> .  ?v0 <http://schema.org/nationality> ?v2 .  }
SELECT * WHERE {  ?v2 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/Genre19> .  ?v2 <http://ogp.me/ns#tag> ?v1 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v2 .  ?v0 <http://ogp.me/ns#tag> ?v1 .  ?v0 <http://schema.org/author> ?v6 .  ?v4 <http://purl.org/stuff/rev#reviewer> ?v6 .  ?v4 <http://purl.org/stuff/rev#rating> ?v5 .  }
SELECT * WHERE {  ?v0 <http://xmlns.com/foaf/age> <http://db.uwaterloo.ca/~galuc/wsdbm/AgeGroup5> .  ?v2 <http://schema.org/editor> ?v0 .  }
SELECT * WHERE {  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/gender> <http://db.uwaterloo.ca/~galuc/wsdbm/Gender1> .  ?v0 <http://purl.org/dc/terms/Location> ?v1 .  ?v0 <http://schema.org/birthDate> ?v2 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/friendOf> ?v0 .  }
SELECT * WHERE {  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/gender> <http://db.uwaterloo.ca/~galuc/wsdbm/Gender1> .  ?v0 <http://purl.org/dc/terms/Location> ?v1 .  ?v0 <http://schema.org/birthDate> ?v2 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/friendOf> ?v0 .  }
SELECT * WHERE {  <http://db.uwaterloo.ca/~galuc/wsdbm/City24> <http://www.geonames.org/ontology#parentCountry> ?v1 .  ?v2 <http://schema.org/eligibleRegion> ?v1 .  ?v4 <http://schema.org/nationality> ?v1 .  ?v2 <http://schema.org/eligibleQuantity> ?v3 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory1> .  ?v0 <http://xmlns.com/foaf/homepage> ?v1 .  ?v0 <http://schema.org/contentRating> ?v3 .  ?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/subscribes> ?v1 .  ?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/gender> ?v5 .  }
SELECT * WHERE {  ?v0 <http://xmlns.com/foaf/age> <http://db.uwaterloo.ca/~galuc/wsdbm/AgeGroup4> .  ?v0 <http://xmlns.com/foaf/givenName> ?v2 .  ?v0 <http://schema.org/email> ?v3 .  ?v0 <http://schema.org/telephone> ?v4 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/subscribes> ?v5 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/userId> ?v6 .  }
SELECT * WHERE {  ?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic108> .  ?v0 <http://ogp.me/ns#title> ?v2 .  ?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/Role2> .  ?v2 <http://schema.org/contactPoint> ?v0 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/gender> ?v3 .  }
SELECT * WHERE {  <http://db.uwaterloo.ca/~galuc/wsdbm/City101> <http://www.geonames.org/ontology#parentCountry> ?v1 .  ?v2 <http://schema.org/eligibleRegion> ?v1 .  ?v4 <http://schema.org/nationality> ?v1 .  ?v2 <http://schema.org/eligibleQuantity> ?v3 .  }
SELECT * WHERE {  ?v0 <http://purl.org/dc/terms/Location> <http://db.uwaterloo.ca/~galuc/wsdbm/City64> .  ?v0 <http://xmlns.com/foaf/homepage> ?v2 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/userId> ?v3 .  }
SELECT * WHERE {  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/gender> <http://db.uwaterloo.ca/~galuc/wsdbm/Gender1> .  ?v0 <http://xmlns.com/foaf/homepage> ?v1 .  ?v0 <http://schema.org/nationality> ?v8 .  ?v2 <http://schema.org/eligibleRegion> ?v8 .  ?v2 <http://purl.org/goodrelations/includes> ?v3 .  ?v4 <http://purl.org/goodrelations/offers> ?v2 .  ?v2 <http://purl.org/goodrelations/serialNumber> ?v5 .  ?v2 <http://purl.org/goodrelations/validThrough> ?v6 .  ?v2 <http://schema.org/eligibleQuantity> ?v7 .  }
SELECT * WHERE {  ?v0 <http://schema.org/eligibleRegion> <http://db.uwaterloo.ca/~galuc/wsdbm/Country13> .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v0 <http://purl.org/goodrelations/price> ?v2 .  ?v0 <http://purl.org/goodrelations/validThrough> ?v3 .  ?v0 <http://schema.org/eligibleQuantity> ?v4 .  ?v1 <http://schema.org/text> ?v6 .  }
SELECT * WHERE {  ?v0 <http://purl.org/dc/terms/Location> <http://db.uwaterloo.ca/~galuc/wsdbm/City108> .  ?v0 <http://xmlns.com/foaf/familyName> ?v2 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/userId> ?v3 .  }
SELECT * WHERE {  ?v2 <http://purl.org/stuff/rev#hasReview> <http://db.uwaterloo.ca/~galuc/wsdbm/Review123602> .  ?v2 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v2 .  ?v0 <http://xmlns.com/foaf/age> ?v1 .  }
SELECT * WHERE {  ?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic233> .  ?v0 <http://purl.org/stuff/rev#hasReview> ?v2 .  ?v0 <http://schema.org/contentRating> ?v8 .  ?v2 <http://purl.org/stuff/rev#rating> ?v3 .  ?v2 <http://purl.org/stuff/rev#reviewer> ?v4 .  ?v2 <http://purl.org/stuff/rev#text> ?v5 .  ?v2 <http://purl.org/stuff/rev#title> ?v6 .  ?v2 <http://purl.org/stuff/rev#totalVotes> ?v7 .  }
SELECT * WHERE {  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/gender> <http://db.uwaterloo.ca/~galuc/wsdbm/Gender1> .  ?v0 <http://purl.org/dc/terms/Location> ?v1 .  ?v0 <http://xmlns.com/foaf/givenName> ?v2 .  ?v0 <http://schema.org/telephone> ?v3 .  }
SELECT * WHERE {  <http://db.uwaterloo.ca/~galuc/wsdbm/Offer3494> <http://schema.org/eligibleRegion> ?v1 .  ?v0 <http://www.geonames.org/ontology#parentCountry> ?v1 .  ?v3 <http://schema.org/nationality> ?v1 .  ?v3 <http://schema.org/jobTitle> ?v4 .  ?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/gender> ?v5 .  }
SELECT * WHERE {  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre15> .  ?v0 <http://xmlns.com/foaf/homepage> ?v1 .  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .  ?v0 <http://schema.org/description> ?v3 .  ?v0 <http://schema.org/expires> ?v4 .  ?v1 <http://schema.org/url> ?v5 .  }
SELECT * WHERE {  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre11> .  ?v0 <http://xmlns.com/foaf/homepage> ?v1 .  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .  ?v0 <http://schema.org/description> ?v3 .  ?v0 <http://schema.org/expires> ?v4 .  ?v1 <http://schema.org/url> ?v5 .  }
SELECT * WHERE {  ?v0 <http://schema.org/eligibleRegion> <http://db.uwaterloo.ca/~galuc/wsdbm/Country1> .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v2 <http://purl.org/goodrelations/offers> ?v0 .  ?v0 <http://purl.org/goodrelations/price> ?v3 .  ?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .  ?v0 <http://purl.org/goodrelations/validFrom> ?v5 .  ?v0 <http://purl.org/goodrelations/validThrough> ?v6 .  ?v0 <http://schema.org/eligibleQuantity> ?v7 .  ?v0 <http://schema.org/priceValidUntil> ?v9 .  }
SELECT * WHERE {  <http://db.uwaterloo.ca/~galuc/wsdbm/User36435> <http://xmlns.com/foaf/age> ?v1 .  }
SELECT * WHERE {  <http://db.uwaterloo.ca/~galuc/wsdbm/User40361> <http://schema.org/nationality> ?v2 .  ?v0 <http://schema.org/eligibleRegion> ?v2 .  ?v0 <http://schema.org/eligibleQuantity> ?v1 .  }
SELECT * WHERE {  ?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic57> .  ?v0 <http://purl.org/stuff/rev#hasReview> ?v2 .  ?v0 <http://schema.org/contentRating> ?v6 .  ?v0 <http://schema.org/description> ?v7 .  ?v0 <http://schema.org/keywords> ?v8 .  ?v2 <http://purl.org/stuff/rev#rating> ?v3 .  ?v2 <http://purl.org/stuff/rev#reviewer> ?v4 .  ?v2 <http://purl.org/stuff/rev#totalVotes> ?v5 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/Role1> .  ?v2 <http://schema.org/contactPoint> ?v0 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/gender> ?v3 .  }
SELECT * WHERE {  ?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic22> .  ?v0 <http://schema.org/caption> ?v2 .  ?v0 <http://schema.org/expires> ?v3 .  ?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseFor> ?v0 .  ?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseDate> ?v5 .  }
SELECT * WHERE {  <http://db.uwaterloo.ca/~galuc/wsdbm/City239> <http://www.geonames.org/ontology#parentCountry> ?v1 .  ?v4 <http://schema.org/eligibleRegion> ?v1 .  ?v9 <http://schema.org/nationality> ?v1 .  ?v2 <http://purl.org/goodrelations/offers> ?v4 .  ?v4 <http://purl.org/goodrelations/serialNumber> ?v5 .  ?v4 <http://schema.org/eligibleQuantity> ?v7 .  ?v4 <http://schema.org/priceValidUntil> ?v10 .  ?v2 <http://purl.org/goodrelations/description> ?v3 .  ?v2 <http://schema.org/aggregateRating> ?v6 .  ?v2 <http://schema.org/legalName> ?v8 .  }
SELECT * WHERE {  <http://db.uwaterloo.ca/~galuc/wsdbm/Purchase76624> <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseFor> ?v0 .  ?v0 <http://ogp.me/ns#title> ?v1 .  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .  ?v0 <http://schema.org/description> ?v3 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v4 .  }
SELECT * WHERE {  ?v0 <http://schema.org/nationality> <http://db.uwaterloo.ca/~galuc/wsdbm/Country1> .  ?v0 <http://xmlns.com/foaf/familyName> ?v1 .  ?v0 <http://schema.org/birthDate> ?v2 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/gender> ?v4 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v5 .  }
SELECT * WHERE {  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/subscribes> <http://db.uwaterloo.ca/~galuc/wsdbm/Website245> .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/userId> ?v2 .  }
SELECT * WHERE {  ?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic154> .  ?v0 <http://xmlns.com/foaf/homepage> ?v1 .  ?v0 <http://ogp.me/ns#title> ?v3 .  ?v0 <http://schema.org/expires> ?v4 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v5 .  ?v6 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .  ?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseFor> ?v0 .  }
SELECT * WHERE {  ?v0 <http://xmlns.com/foaf/age> <http://db.uwaterloo.ca/~galuc/wsdbm/AgeGroup2> .  ?v0 <http://xmlns.com/foaf/givenName> ?v2 .  ?v0 <http://schema.org/email> ?v3 .  ?v0 <http://schema.org/nationality> ?v4 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/friendOf> ?v0 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/gender> ?v5 .  }
SELECT * WHERE {  ?v0 <http://schema.org/eligibleRegion> <http://db.uwaterloo.ca/~galuc/wsdbm/Country19> .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v2 <http://purl.org/goodrelations/offers> ?v0 .  ?v0 <http://purl.org/goodrelations/validFrom> ?v3 .  ?v0 <http://purl.org/goodrelations/validThrough> ?v4 .  ?v0 <http://schema.org/eligibleQuantity> ?v5 .  ?v0 <http://schema.org/priceValidUntil> ?v7 .  }
SELECT * WHERE {  ?v0 <http://xmlns.com/foaf/age> <http://db.uwaterloo.ca/~galuc/wsdbm/AgeGroup6> .  ?v0 <http://xmlns.com/foaf/givenName> ?v2 .  ?v0 <http://schema.org/email> ?v3 .  ?v0 <http://schema.org/telephone> ?v4 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/subscribes> ?v5 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/userId> ?v6 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory0> .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v2 .  ?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .  }
SELECT * WHERE {  ?v0 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language14> .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v2 .  }
SELECT * WHERE {  ?v0 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language5> .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v2 .  }
SELECT * WHERE {  <http://db.uwaterloo.ca/~galuc/wsdbm/Retailer483> <http://purl.org/goodrelations/offers> ?v1 .  ?v1 <http://purl.org/goodrelations/price> ?v2 .  ?v1 <http://purl.org/goodrelations/serialNumber> ?v3 .  ?v1 <http://schema.org/eligibleRegion> ?v4 .  }
SELECT * WHERE {  ?v0 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language6> .  ?v0 <http://purl.org/stuff/rev#hasReview> ?v1 .  ?v1 <http://purl.org/stuff/rev#title> ?v2 .  }
SELECT * WHERE {  ?v0 <http://purl.org/dc/terms/Location> <http://db.uwaterloo.ca/~galuc/wsdbm/City105> .  ?v0 <http://xmlns.com/foaf/age> ?v2 .  ?v0 <http://schema.org/birthDate> ?v3 .  }
SELECT * WHERE {  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre132> .  ?v0 <http://xmlns.com/foaf/homepage> ?v1 .  ?v0 <http://ogp.me/ns#tag> ?v2 .  ?v0 <http://schema.org/keywords> ?v3 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory12> .  ?v0 <http://ogp.me/ns#tag> ?v1 .  }
SELECT * WHERE {  ?v2 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/Role2> .  ?v0 <http://schema.org/author> ?v2 .  ?v2 <http://schema.org/email> ?v5 .  ?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/friendOf> ?v2 .  ?v0 <http://ogp.me/ns#tag> ?v1 .  ?v0 <http://schema.org/contentSize> ?v4 .  }
SELECT * WHERE {  <http://db.uwaterloo.ca/~galuc/wsdbm/Retailer146> <http://purl.org/goodrelations/offers> ?v0 .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v0 <http://purl.org/goodrelations/serialNumber> ?v3 .  ?v0 <http://purl.org/goodrelations/validThrough> ?v4 .  ?v0 <http://schema.org/eligibleQuantity> ?v5 .  ?v0 <http://schema.org/priceValidUntil> ?v6 .  }
SELECT * WHERE {  ?v0 <http://schema.org/eligibleRegion> <http://db.uwaterloo.ca/~galuc/wsdbm/Country18> .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v2 <http://purl.org/goodrelations/offers> ?v0 .  ?v0 <http://purl.org/goodrelations/validFrom> ?v3 .  ?v0 <http://purl.org/goodrelations/validThrough> ?v4 .  ?v0 <http://schema.org/eligibleQuantity> ?v5 .  ?v0 <http://schema.org/priceValidUntil> ?v7 .  }
SELECT * WHERE {  ?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/Genre20> .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v3 .  ?v0 <http://xmlns.com/foaf/homepage> ?v1 .  ?v2 <http://purl.org/goodrelations/includes> ?v0 .  ?v0 <http://schema.org/caption> ?v5 .  ?v0 <http://schema.org/contentRating> ?v6 .  ?v0 <http://schema.org/text> ?v7 .  ?v8 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .  }
SELECT * WHERE {  <http://db.uwaterloo.ca/~galuc/wsdbm/Purchase99462> <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseFor> ?v0 .  ?v0 <http://ogp.me/ns#tag> ?v1 .  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .  ?v0 <http://schema.org/text> ?v4 .  ?v2 <http://ogp.me/ns#tag> ?v1 .  }
SELECT * WHERE {  ?v0 <http://schema.org/eligibleRegion> <http://db.uwaterloo.ca/~galuc/wsdbm/Country16> .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v0 <http://purl.org/goodrelations/price> ?v2 .  ?v0 <http://purl.org/goodrelations/validThrough> ?v3 .  ?v0 <http://schema.org/eligibleQuantity> ?v4 .  ?v1 <http://schema.org/text> ?v6 .  }
SELECT * WHERE {  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre50> .  ?v0 <http://ogp.me/ns#title> ?v1 .  ?v0 <http://schema.org/contentRating> ?v2 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/Role0> .  ?v0 <http://schema.org/nationality> ?v2 .  }
SELECT * WHERE {  ?v4 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic170> .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v4 .  ?v0 <http://xmlns.com/foaf/age> ?v1 .  ?v0 <http://xmlns.com/foaf/familyName> ?v2 .  ?v0 <http://xmlns.com/foaf/homepage> ?v3 .  }
SELECT * WHERE {  ?v4 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/Role2> .  ?v4 <http://schema.org/nationality> ?v7 .  ?v1 <http://schema.org/eligibleRegion> ?v7 .  ?v0 <http://purl.org/goodrelations/offers> ?v1 .  ?v1 <http://purl.org/goodrelations/validFrom> ?v2 .  ?v1 <http://purl.org/goodrelations/validThrough> ?v3 .  ?v1 <http://schema.org/eligibleQuantity> ?v6 .  ?v1 <http://schema.org/priceValidUntil> ?v8 .  }
SELECT * WHERE {  ?v0 <http://schema.org/eligibleRegion> <http://db.uwaterloo.ca/~galuc/wsdbm/Country2> .  ?v0 <http://purl.org/goodrelations/validThrough> ?v1 .  ?v0 <http://schema.org/eligibleQuantity> ?v2 .  }
SELECT * WHERE {  <http://db.uwaterloo.ca/~galuc/wsdbm/User40774> <http://schema.org/nationality> ?v2 .  ?v0 <http://schema.org/eligibleRegion> ?v2 .  ?v0 <http://schema.org/eligibleQuantity> ?v1 .  }
SELECT * WHERE {  ?v0 <http://schema.org/eligibleRegion> <http://db.uwaterloo.ca/~galuc/wsdbm/Country13> .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v2 <http://purl.org/goodrelations/offers> ?v0 .  ?v0 <http://purl.org/goodrelations/validFrom> ?v3 .  ?v0 <http://purl.org/goodrelations/validThrough> ?v4 .  ?v0 <http://schema.org/eligibleQuantity> ?v5 .  ?v0 <http://schema.org/priceValidUntil> ?v7 .  }
SELECT * WHERE {  <http://db.uwaterloo.ca/~galuc/wsdbm/Purchase20566> <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseFor> ?v0 .  ?v0 <http://ogp.me/ns#title> ?v1 .  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .  ?v0 <http://schema.org/description> ?v3 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v4 .  }
SELECT * WHERE {  ?v5 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/Role1> .  ?v1 <http://schema.org/editor> ?v5 .  ?v5 <http://db.uwaterloo.ca/~galuc/wsdbm/gender> ?v8 .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v1 <http://ogp.me/ns#title> ?v4 .  ?v1 <http://schema.org/expires> ?v7 .  ?v0 <http://purl.org/goodrelations/serialNumber> ?v2 .  ?v0 <http://purl.org/goodrelations/validFrom> ?v3 .  }
SELECT * WHERE {  ?v5 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/Role2> .  ?v1 <http://schema.org/editor> ?v5 .  ?v5 <http://db.uwaterloo.ca/~galuc/wsdbm/gender> ?v8 .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v1 <http://ogp.me/ns#title> ?v4 .  ?v1 <http://schema.org/expires> ?v7 .  ?v0 <http://purl.org/goodrelations/serialNumber> ?v2 .  ?v0 <http://purl.org/goodrelations/validFrom> ?v3 .  }
SELECT * WHERE {  ?v2 <http://schema.org/eligibleRegion> <http://db.uwaterloo.ca/~galuc/wsdbm/Country19> .  ?v0 <http://purl.org/goodrelations/offers> ?v2 .  ?v2 <http://purl.org/goodrelations/price> ?v3 .  ?v2 <http://purl.org/goodrelations/validFrom> ?v4 .  ?v2 <http://purl.org/goodrelations/validThrough> ?v5 .  ?v0 <http://purl.org/goodrelations/name> ?v1 .  ?v0 <http://schema.org/contactPoint> ?v8 .  ?v0 <http://schema.org/email> ?v10 .  ?v0 <http://schema.org/openingHours> ?v11 .  ?v6 <http://purl.org/stuff/rev#reviewer> ?v8 .  ?v6 <http://purl.org/stuff/rev#rating> ?v7 .  }
SELECT * WHERE {  ?v2 <http://purl.org/stuff/rev#hasReview> <http://db.uwaterloo.ca/~galuc/wsdbm/Review91939> .  ?v2 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v2 .  ?v0 <http://xmlns.com/foaf/age> ?v1 .  }
SELECT * WHERE {  ?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory3> .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v1 <http://schema.org/text> ?v3 .  }
SELECT * WHERE {  ?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v1 <http://purl.org/stuff/rev#hasReview> ?v3 .  ?v1 <http://schema.org/contentSize> ?v9 .  ?v3 <http://purl.org/stuff/rev#rating> ?v4 .  ?v3 <http://purl.org/stuff/rev#reviewer> ?v5 .  ?v3 <http://purl.org/stuff/rev#text> ?v6 .  ?v3 <http://purl.org/stuff/rev#title> ?v7 .  ?v3 <http://purl.org/stuff/rev#totalVotes> ?v8 .  }
SELECT * WHERE {  ?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic57> .  ?v0 <http://schema.org/caption> ?v2 .  ?v0 <http://schema.org/expires> ?v3 .  ?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseFor> ?v0 .  ?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseDate> ?v5 .  }
SELECT * WHERE {  ?v0 <http://xmlns.com/foaf/age> <http://db.uwaterloo.ca/~galuc/wsdbm/AgeGroup4> .  ?v0 <http://xmlns.com/foaf/givenName> ?v2 .  ?v0 <http://schema.org/email> ?v3 .  ?v0 <http://schema.org/telephone> ?v4 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/subscribes> ?v5 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/userId> ?v6 .  }
SELECT * WHERE {  ?v0 <http://schema.org/eligibleRegion> <http://db.uwaterloo.ca/~galuc/wsdbm/Country19> .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v2 <http://purl.org/goodrelations/offers> ?v0 .  ?v0 <http://purl.org/goodrelations/price> ?v3 .  ?v0 <http://purl.org/goodrelations/serialNumber> ?v4 .  ?v0 <http://purl.org/goodrelations/validFrom> ?v5 .  ?v0 <http://purl.org/goodrelations/validThrough> ?v6 .  ?v0 <http://schema.org/eligibleQuantity> ?v7 .  ?v0 <http://schema.org/priceValidUntil> ?v9 .  }
SELECT * WHERE {  <http://db.uwaterloo.ca/~galuc/wsdbm/Offer46426> <http://purl.org/goodrelations/includes> ?v1 .  ?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .  ?v1 <http://schema.org/keywords> ?v3 .  }
SELECT * WHERE {  ?v0 <http://xmlns.com/foaf/age> <http://db.uwaterloo.ca/~galuc/wsdbm/AgeGroup7> .  ?v2 <http://schema.org/author> ?v0 .  ?v0 <http://schema.org/telephone> ?v3 .  }
SELECT * WHERE {  <http://db.uwaterloo.ca/~galuc/wsdbm/User76214> <http://schema.org/nationality> ?v3 .  ?v0 <http://schema.org/eligibleRegion> ?v3 .  ?v0 <http://purl.org/goodrelations/serialNumber> ?v1 .  ?v0 <http://purl.org/goodrelations/validThrough> ?v2 .  }
SELECT * WHERE {  ?v0 <http://xmlns.com/foaf/age> <http://db.uwaterloo.ca/~galuc/wsdbm/AgeGroup3> .  ?v0 <http://xmlns.com/foaf/homepage> ?v2 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/userId> ?v3 .  }
SELECT * WHERE {  ?v2 <http://purl.org/stuff/rev#hasReview> <http://db.uwaterloo.ca/~galuc/wsdbm/Review15565> .  ?v2 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v3 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v2 .  ?v0 <http://xmlns.com/foaf/age> ?v1 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory1> .  ?v0 <http://xmlns.com/foaf/homepage> ?v1 .  ?v0 <http://schema.org/contentRating> ?v3 .  ?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/subscribes> ?v1 .  ?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/gender> ?v5 .  }
SELECT * WHERE {  ?v0 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language21> .  ?v0 <http://purl.org/stuff/rev#hasReview> ?v1 .  ?v1 <http://purl.org/stuff/rev#title> ?v2 .  }
SELECT * WHERE {  ?v2 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/Role2> .  ?v0 <http://schema.org/author> ?v2 .  ?v2 <http://schema.org/email> ?v5 .  ?v2 <http://db.uwaterloo.ca/~galuc/wsdbm/friendOf> ?v2 .  ?v0 <http://ogp.me/ns#tag> ?v1 .  ?v0 <http://schema.org/contentSize> ?v4 .  }
SELECT * WHERE {  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/gender> <http://db.uwaterloo.ca/~galuc/wsdbm/Gender1> .  ?v0 <http://xmlns.com/foaf/homepage> ?v1 .  ?v0 <http://schema.org/nationality> ?v8 .  ?v2 <http://schema.org/eligibleRegion> ?v8 .  ?v2 <http://purl.org/goodrelations/includes> ?v3 .  ?v4 <http://purl.org/goodrelations/offers> ?v2 .  ?v2 <http://purl.org/goodrelations/serialNumber> ?v5 .  ?v2 <http://purl.org/goodrelations/validThrough> ?v6 .  ?v2 <http://schema.org/eligibleQuantity> ?v7 .  }
SELECT * WHERE {  ?v0 <http://schema.org/language> <http://db.uwaterloo.ca/~galuc/wsdbm/Language8> .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v2 .  }
SELECT * WHERE {  <http://db.uwaterloo.ca/~galuc/wsdbm/Product17840> <http://ogp.me/ns#title> ?v1 .  }
SELECT * WHERE {  ?v2 <http://schema.org/eligibleRegion> <http://db.uwaterloo.ca/~galuc/wsdbm/Country7> .  ?v2 <http://purl.org/goodrelations/includes> ?v3 .  ?v0 <http://purl.org/goodrelations/offers> ?v2 .  ?v2 <http://purl.org/goodrelations/validThrough> ?v4 .  ?v2 <http://schema.org/eligibleQuantity> ?v6 .  ?v2 <http://schema.org/priceValidUntil> ?v9 .  ?v0 <http://purl.org/goodrelations/description> ?v1 .  ?v0 <http://schema.org/aggregateRating> ?v5 .  ?v0 <http://schema.org/faxNumber> ?v8 .  ?v0 <http://schema.org/telephone> ?v10 .  }
SELECT * WHERE {  ?v0 <http://purl.org/goodrelations/includes> <http://db.uwaterloo.ca/~galuc/wsdbm/Product1826> .  ?v0 <http://purl.org/goodrelations/price> ?v2 .  ?v0 <http://schema.org/eligibleQuantity> ?v3 .  ?v0 <http://schema.org/priceValidUntil> ?v4 .  }
SELECT * WHERE {  ?v0 <http://purl.org/dc/terms/Location> <http://db.uwaterloo.ca/~galuc/wsdbm/City239> .  ?v0 <http://xmlns.com/foaf/age> ?v2 .  ?v0 <http://schema.org/birthDate> ?v3 .  }
SELECT * WHERE {  <http://db.uwaterloo.ca/~galuc/wsdbm/SubGenre17> <http://ogp.me/ns#tag> ?v1 .  ?v0 <http://ogp.me/ns#tag> ?v1 .  ?v0 <http://schema.org/description> ?v3 .  }
SELECT * WHERE {  ?v0 <http://ogp.me/ns#tag> <http://db.uwaterloo.ca/~galuc/wsdbm/Topic154> .  ?v0 <http://xmlns.com/foaf/homepage> ?v1 .  ?v0 <http://ogp.me/ns#title> ?v3 .  ?v0 <http://schema.org/expires> ?v4 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v5 .  ?v6 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .  ?v7 <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseFor> ?v0 .  }
SELECT * WHERE {  <http://db.uwaterloo.ca/~galuc/wsdbm/Purchase79646> <http://db.uwaterloo.ca/~galuc/wsdbm/purchaseFor> ?v0 .  ?v0 <http://ogp.me/ns#title> ?v1 .  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v2 .  ?v0 <http://schema.org/description> ?v3 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v4 .  }
