#!/usr/bin/env node
var args = process.argv.slice(2);
if (args.length < 1 || args.length > 3 || /^--?h(elp)?$/.test(args[0])) {
  console.log('usage: ./slow-proxy targetPort proxyPort delay');
  return process.exit(1);
}

var http = require('http'),
  httpProxy = require('http-proxy');

var proxy = httpProxy.createProxyServer({
    target: {
      host: 'localhost',
      port: args[0]
    }
  });

http.createServer(function (req, res) {
  setTimeout(function () {
    proxy.web(req, res);
  }, args[2]);
}).listen(args[1], function () {
  console.log('proxy %d listening on port %d', process.pid, args[1]);
});
